### ISSUE TITLE
Proposal: Use kabanero operator java bindings

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-command-line-services#103]
There are generated Java wrappers around the operator CRDs that are published to Maven Central.  We should consider using these when we read the Kabanero CR instances from Kubernetes, instead of the way we do it now where we pass around hash maps containing key/value pairs of the various YAMLs.  

This branch shows how one would convert the command line services to use the Java mappings (I've converted all of the existing code).
https://github.com/kabanero-io/kabanero-command-line-services/compare/master...kaczyns:kabaneroMappings?expand=1

To import the mappings, include the following in the pom.xml:
```xml
    <dependency>
      <groupId>io.kabanero</groupId>
      <artifactId>operator-java-bindings</artifactId>
      <version>0.0.1</version>
    </dependency>
```

**Comment by davco01a** [comment]
completed
