### ISSUE TITLE
CLI Service support for reading a stack index hosted in GHE

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-command-line-services#112]
In release 0.7.0 the Kabanero CRD will introduce a second way that a user can point to the stack hub index, using the Github API.  This allows someone to point at GHE which is protected via OAuth.  The CLI service will need to support reading this second way from the Kabanero CR instance, and selecting the correct secret to use (the secret contains the PAT that is used to authenticate).

See kabanero-io/kabanero-operator#253 for some more information.  The first comment has a checklist which links to several other issues that describe the approach that we are taking here.

I wanted to get this issue opened now and linked to the epic so that we understand all of the affected components at the beginning of the release.

**Comment by davco01a** [comment]
operator related issues:

https://github.com/kabanero-io/kabanero-operator/issues/469

**Comment by davco01a** [comment]
to gather kubernetes secret ( the PAT ) for GHE API call:

https://github.com/kabanero-io/kabanero-operator/issues/468

**Comment by davco01a** [comment]
0.7.0-snapshot for latest operator bindings

**Comment by davco01a** [comment]
merged
