### ISSUE TITLE
Very old version of Liberty Maven plugin?

### ISSUE THREAD

**Issue by plainchanter** [kabanero-io/kabanero-command-line-services#114]
During bringup on a new platform, I am seeing Java NPEs from the WAS Maven plugin which, judging from the pom.xml file, is at version 2.1.2 (December 2017)

From Cheryl King:

I strongly suggest moving up to at least version 2.7, which was released in June 2019 (that is the last release we made with the old group id).

**Comment by davco01a** [comment]
OK

**Comment by davco01a** [comment]
thanks that seems to have helped
