### ISSUE TITLE
use KabaneroSpecStackVersions instead of KabaneroStatusStackVersions

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line-services#115]
use KabaneroSpecStackVersions instead of KabaneroStatusStackVersions

The delete and activate functions were using the wrong type for updating the version metadata
during SYNC processing

**Comment by marikaj123** [comment]
Going into Kabanero GMC 0.6.0

**Comment by davco01a** [comment]
fixed
