### ISSUE TITLE
document the  cli service REST API

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-command-line-services#150]
Thee CLI Service REST API should be documented.   I don't see anything in the README.md currently.

One approach:   In the README, add a high level description of the API, and then point to the test/postman collection for the details.    Assuming postman collections can have comments, add comments to the postman collection to note the intention for each REST call.

**Comment by davco01a** [comment]
ok

**Comment by davco01a** [comment]
merged
