### ISSUE TITLE
Generalized method of getting digests using OCI APIs

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line-services#155]
Generalized method of getting digests using OCI APIs

**Comment by s1cyan** [comment]
https://github.com/kabanero-io/kabanero-command-line-services/blob/6581128eeafc0701277f887e100214c4f3cc6376/src/main/java/application/rest/StackUtils.java#L80

**Comment by davco01a** [comment]
merged: https://github.com/kabanero-io/kabanero-command-line-services/pull/160
