### ISSUE TITLE
Allow CLI service to continue working even without container registry secret

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line-services#180]
Allow CLI service to continue working even without container registry secret

Just display unknown for digest check if no container registry secret has been setup

**Comment by jgawor** [comment]
@davco01a what happens if my registry does not require authentication?

**Comment by davco01a** [comment]
Good question, I look into that variation too

**Comment by mtamboli** [comment]
> @davco01a what happens if my registry does not require authentication?

Yes, that is the discussion I am having with @davco01a if we really need registry secret to check digests when using public docker hub for stack images.

**Comment by davco01a** [comment]
Yes, coded to work with and without credentials (secret) now
