### ISSUE TITLE
Error message improvements when apiURL is not correct

### ISSUE THREAD

**Issue by mtamboli** [kabanero-io/kabanero-command-line-services#186]
Below error condition happens when the apiURL provided for GitHub is incorrect. It will be helpful to give a more clear error message to user for debugging purposes.

```
./kabanero login  <server> -u <user>
Password:
login failed, you may want to check your authorization configuration. Check the CLI Service pod for more information.
```
But as suggested, I look at the CLI pod and the message is as below.
```
[err] An error occurred. An error occurred during authentication for user Unexpected char 60 at (line no=1, column no=1, offset=0)
{message=An internal error occurred.}
```
Can we elaborate/enhance this message to be more specific and helpful?

**Comment by mtamboli** [comment]
[cli_0506.log](https://github.com/kabanero-io/kabanero-command-line-services/files/4587246/cli_0506.log)

**Comment by davco01a** [comment]
fixed by: https://github.com/kabanero-io/kabanero-command-line-services/pull/188
