### ISSUE TITLE
Kabanero command line Micro Service

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line-services#2]
Kabanero command line Micro Service to support calls from GO thin client and authenticate to Github, perform IO to git hub collections and execute functions into kubernetes to activate, deactivate and remove collections.

**Comment by davco01a** [comment]
OK Pod running with Chunlong's security service
Acquiring JWT and returning to GO thin client

Invocation of functional endpoints working

Call to Kube to list out namespaces working

Working on get calls to Github

**Comment by marikaj123** [comment]
For release Aug-26

**Comment by davco01a** [comment]
micro service completed
