### ISSUE TITLE
Automated Build and automated Operator install of microservice

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line-services#29]
Automated Build and automated Operator install of microservice

**Comment by tseelbach** [comment]
@davco01a i think that for this to be completed we need a travis build of CLI Service, and then at least a runbook/process to publish a GitHub Release of the Docker image so that the Kabanero Operator can pick it up

**Comment by davco01a** [comment]
Fully automated with Docker build and push to Docker hub

**Comment by davco01a** [comment]
Working with Gary Picher to set up release docker push

**Comment by davco01a** [comment]
done
