### ISSUE TITLE
command-line-service footprint too big

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-command-line-services#33]
initial bringup indicates that command-line service is too big.  Need to investigate what is causing this

**Comment by brutif** [comment]
we don't need the full microprofile 2.0, could I think trim it down to just 
```
<feature>jaxrs-2.1</feature>
        <feature>mpconfig-1.3</feature>
        <feature>mpjwt-1.1</feature>
```

**Comment by davco01a** [comment]
using UBI in docker file dropped footpring to 271mb, Alan says this is sufficient

**Comment by davco01a** [comment]
Reducing the feature set from:

```
<featureManager>
        <feature>appSecurity-2.0</feature> 
        <feature>microProfile-2.0</feature>
    </featureManager>
```

to 

```
<featureManager>
        <feature>jaxrs-2.1</feature>
        <feature>mpConfig-1.3</feature>
        <feature>mpJwt-1.1</feature>
        <feature>json-1.0</feature>
  </featureManager>
```

Saved 3M

**Comment by davco01a** [comment]
[root@thills1 ~]# kubectl top pod kabanero-cli-654564cb49-q2hhj
NAME                            CPU(cores)   MEMORY(bytes)   
kabanero-cli-654564cb49-q2hhj   7m           321Mi           
[root@thills1 ~]#
