### ISSUE TITLE
Submit the microservice container to Redhat for certification

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-command-line-services#36]
The container for the microservice needs to be submitted to Redhat for certification.

**Comment by tseelbach** [comment]
see this issue for some reference info: https://github.com/kabanero-io/kabanero-operator/issues/140

**Comment by davco01a** [comment]
Project created
image uploaded
7 of 9 questions completed at:  https://connect.redhat.com/project/1405481/checklist

**Comment by davco01a** [comment]
@garypicher says we're done, he'll take it from here
