### ISSUE TITLE
Onboard should return message with a hyperlink to Tekton dashboard along with existing message

### ISSUE THREAD

**Issue by brianxjx** [kabanero-io/kabanero-command-line-services#38]
Current cli-svc invocations make use of custom resources via the openshift apiClient.  In order to configure a webhook programmatically, an OAuth handshake is needed to properly invoke the Tekton Webhook extension REST endpoint.

**Comment by davco01a** [comment]
Due to the OAuth complications it would be good if we could just return a link for Champ to use to navigate to the Tekton dashboard

**Comment by davco01a** [comment]
This is how the Kabanero operator gets the route in GO lang:

https://github.com/kabanero-io/kabanero-operator/blob/f636b000d11bd71994ae57509550ed412ac8f36b/pkg/controller/kabaneroplatform/cli.go#L176

**Comment by davco01a** [comment]
see how we currently get collection URL out of the Kabanero object:

https://github.com/kabanero-io/kabanero-command-line-services/blob/cc4d5c59f3529f3a5073675dc763ab68f7f67475/src/main/java/application/rest/CollectionsUtils.java#L124

Something similar may work reading out of a Tekton object

**Comment by brianxjx** [comment]
https://github.com/kabanero-io/kabanero-command-line-services/pull/89/

https://github.com/kabanero-io/kabanero-operator/issues/301

**Comment by davco01a** [comment]
done
