### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-command-line-services#64]
The README doesn't talk about what this project is about, how to build it, how to use it, etc.

**Comment by davco01a** [comment]
there is a build-help.md that explains how to build it.  I'll add description info about the project

**Comment by jgawor** [comment]
build-help.md shows how to build via Travis but not if I want to build this manually for testing purposes.

**Comment by tseelbach** [comment]
additional README updates:
/health endpoint is documented twice.  It should only be mentioned once
How does one find the endpoint for CLI to connect to?
Provide a link to build-help.md, not just text
"Credentials are either taken from the VCAP_SERVICE" seems wrong
Notices section  seems unneeded.
why the "ibm cloud powered" badge?

**Comment by davco01a** [comment]
addressed comments

**Comment by davco01a** [comment]
https://github.com/kabanero-io/kabanero-command-line-services/pull/68

**Comment by davco01a** [comment]
merged
