### ISSUE TITLE
Unnecessary files / repeatable builds

### ISSUE THREAD

**Issue by jgawor** [kabanero-io/kabanero-command-line-services#65]
* The `target` should not be checked in or contain any important files. That directory is deleted whenever `mvn clean` is executed. Because of that, repeatable builds are broken right now. 
* Is `temp.json` needed?
* `Makefile` references `davco01a` DockerHub organization
* Don't think `dependency-report` in Makefile is needed.

**Comment by davco01a** [comment]
ok

**Comment by davco01a** [comment]
merged
