### ISSUE TITLE
cleanup build process

### ISSUE THREAD

**Issue by tseelbach** [kabanero-io/kabanero-command-line-services#67]
Seems there is leftover stuff: which of the following are used/needed?
Makefile
chart/*
.factorypath
Jenkinsfile (also talks about KabCollections)

Also: pom.xml has CF and bluemix references

**Comment by davco01a** [comment]
https://github.com/kabanero-io/kabanero-command-line-services/pull/68

**Comment by davco01a** [comment]
merged
