### ISSUE TITLE
Support collection deactivation when the collection is still present in the repository

### ISSUE THREAD

**Issue by kaczyns** [kabanero-io/kabanero-command-line-services#69]
See kabanero-io/kabanero-foundation#85 and kabanero-io/kabanero-operator#229.  When creating `kind: Collection` instances, a new `desiredState` attribute should be set to `active`.  When deactivating a collection, rather than delete the instance, the `desiredState` should be set to `inactive`.

The kabanero-operator will change in this release to support reading the `desiredState` attribute.

Previous versions of the command line services should delete the `kind: Collection` instance on deactivation, as the attribute will not be rolled back to previous versions of Kabanero.  This should not be an issue since previous versions of Kabanero will be using the previous version of the CLI services container.

**Comment by davco01a** [comment]
done
