### ISSUE TITLE
CLI Service should dynamically introspect version number programmatically

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line-services#76]
The CLI dynamically obtains the version from the build.

The CLI service should also obtain the based on the TRAVIS_TAG, it is currently hard-coded.

**Comment by stephenkinder** [comment]
@davco01a can you clarify this issue a bit more, please?  I get that this issue likely related to the CLI, perhaps a simple example?  Are you expecting the version to be created as part of a build or tagged as a release and that the CLI should get that info from the build somehow?

**Comment by davco01a** [comment]
The CLI gets this info from the build currently

The CLI service now has to do the same thing, right now version is hard coded and not based on the TRAVIS_TAG

**Comment by davco01a** [comment]
merged
