### ISSUE TITLE
CLI list command shows deleted collection twice. 

### ISSUE THREAD

**Issue by mcurran-us** [kabanero-io/kabanero-command-line-services#78]
I deleted a collection from my curated collection and did a list.  The deleted collection displays twice in the non-curated collection list, once as active and once as obsolete.
Collection Name                 Version Status
----                            ----    ----
java-microprofile               0.2.18  active
**java-spring-boot2               0.3.15  active**
java-websphere-traditional      0.1.1   active
nodejs                          0.2.5   active
nodejs-express                  0.2.7   active
nodejs-loopback                 0.1.5   active
**java-spring-boot2               0.3.15  obsolete**
Curated Collections             Version
----                            ----
java-microprofile               0.2.18
java-websphere-traditional      0.1.1
nodejs-express                  0.2.7
nodejs-loopback                 0.1.5
nodejs                          0.2.5

**Comment by davco01a** [comment]
Hopefully this will resolve with the updates coming in: https://github.com/kabanero-io/kabanero-command-line-services/issues/77

**Comment by davco01a** [comment]
did not recreate with new support
