### ISSUE TITLE
  deactivate could check that status actually gets changed to inactive, not just desiredState

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line-services#88]
Currently cli-service deactivate checks the desiredState.  It does not check the "status" to see if the stack actually is deactivated.  This defect is to enhance deactivate to check that the stack actually gets deactivated

**Comment by davco01a** [comment]
This needs to be assessed if it's actually necessary, came out of potential collections controller issue

**Comment by davco01a** [comment]
will probably require a sleep of 5-10 seconds so they collections controller can make the status change

**Comment by davco01a** [comment]
check in with @mezarin also may be changing deactivate to delete, check with design and/or @kaczyns

**Comment by marikaj123** [comment]
It was referenced by 'Bug: Kabanero CLI - deactivate command needs to report if actual deactivate happened #123'

**Comment by davco01a** [comment]
this was previously a problem in the collections controller that does not appear to be recurring.
That said it would be slow to poll the stack status while waiting for the stack controller to update the state of the stack.   The same information can be gleaned from the LIST command.

We don't want to put a peformance bottleneck on the deactivate command.

**Comment by davco01a** [comment]
https://github.com/kabanero-io/kabanero-command-line-services/issues/128
