### ISSUE TITLE
Detect if Git team authorization is not configured

### ISSUE THREAD

**Issue by davco01a** [kabanero-io/kabanero-command-line-services#92]
Detect if this has not been configured:

https://kabanero.io/docs/ref/general/github-authorization.html

and return an http code and json response to CLI so it can display the appropriate msg

**Comment by davco01a** [comment]
See code here to read the Kabanero CRD to check if authorizations have been configured:

https://github.com/kabanero-io/kabanero-command-line-services/blob/02c8f6eb2e48f0381c8a9be2684c83c0432dd405/src/main/java/application/rest/CollectionsUtils.java#L158

**Comment by brutif** [comment]
addressed by #93 and Dave's going to do some add'l checking.

**Comment by davco01a** [comment]
The login service will return an http account 539 code and a json response:

```
“message”: “An error occurred. An error occurred during authentication for user [davco01a]. The Github configuration is not complete: No Github teams have been defined.”
```

**Comment by davco01a** [comment]
Code is merged closing this issue.

@s1cyan Please note I left the Kabanero CRD with a messed up github config so that you can test the 539 code and json response on:

kabanero-cli-kabanero.apps.grivet.os.fyre.ibm.com
